### PR TITLE
[WIP] NEW: Output to a directory in build to make a release.

### PR DESCRIPTION
**Pull request by fire**
Work in progress installer.

Deploys using a batch script.

Please see if the version generation is correct, I'm currently using a timestamp.

[Edited] 

Use by going to the build directory and copying `maya2gltf_2019_10_02_13_12_maya_2019.zip` for example.

### CODE REVIEW

**Comment by Ziriax** [comment]
I didn't know you were also fluent in cmake, amazing!

I actually wanted to use the git tag for the version number, and also include the git revision in the package name, so it is easy to see what commit generated the package

Something like this: https://cmake.org/pipermail/cmake/2018-October/068389.html

In the master branch I use an msbuild task to modify the cpp and mel files to expose the version and git revision to the compiler, so that the build plugin and Mel UI also show the version info. I wasn't able to figure out how to do that with cmake.

**Comment by fire** [comment]
Here's the proposed design:

* use the git tag for the version number
* include the git revision and version number in the package name
* generate a cpp include file that includes the version and git revision to the compiler
* generate a mel script that includes the version and git revision

**Comment by Ziriax** [comment]
Perfect

**Comment by fire** [comment]
Did:

* use the git tag for the version number
* [edited] if a tag does not exist, use the "master" string
* truncate the git revision string to a [short hash] characters
* include the git revision and version number in the package name

Working on:

* generate a cpp include file that includes the version and git revision to the compiler
* generate a mel script that includes the version and git revision

**Comment by fire** [comment]
Mel versions and c++ versions are in now.

image

image

**Pull request merged**
