### PR TITLE
Don't create an non-existent blend shape.

### PR DESCRIPTION
**Pull request by fire**
If a plug does not exist at the given Index, Maya will create a plug at that index. Do not do this.

Is there a reason why this uses logical indexes?

@Ziriax

### CODE REVIEW

**Comment by fire** [comment]
Forgot to state the problem:

A few blank blend shape will be created during time of export and actual blend shape will get replaced by them.

A few blank blend shapes are create during the time of the export and then the real blend shapes are replaced by these blank ones.

**Comment by fire** [comment]
`const auto numWeights = m_weightArrayPlug.evaluateNumElements(&status);`

In my sample, numWeights is two more than the expected shapes. So the code will iterate and throw for the last two plugs. 

The elementByPhysicalIndex will return an error status and then the code skips the plug.

Will you have a successor? What happens to this repository? Will WonderMedia allow there to be an Github organization that has the assets of maya2glTF transferred to it?

I was hoping to have someone review the code for gltf2 importing, updating collada2gltf and making binary releases.

**Comment by fire** [comment]
Can we connect off github?

**Comment by fire** [comment]
@Ziriax I wasn't able to get my plan for further contributions to be approved. However, feel free to take this branch and improve the code.

We're switching to using Godot Engine's custom developed FBX importer.

**Comment by Ziriax** [comment]
@fire Thanks for letting me know, and good luck!

**Pull request closed without merging**
